---
layout: post
title: Go Error
subtitle: 错误处理
date: 2019-07-31
categories: go
cover: 
tags: all go defer error
---

> 读《Go语言高级编程》笔记

### 普通错误
go中最正统的错误处理是返回参数中带一个错误类型参数
```go
func run() (param interface{}, err error){
	err = f1()
	if err != nil {
		return err
	}

	err = f2()
	if err != nil {
		return err
	}
	return nil
}
```

### 异常
然而我们有时候会碰到无法预料的异常，此时我们则需要通过defer与recover配合，获取到崩溃信息并恢复程序运行
```go
func ParseJSON(input string) (s *Syntax, err error) {
	defer func() {
		if p := recover(); p != nil {
			err = fmt.Errorf("JSON: internal error: %v", p)
		}
	}()
	// ...parser...
}
```
`recover()`函数必须在defer中运行，并且必须与defer有且仅有一层函数间隔。

即以下几种写法都获取不到异常信息
```go
func main() {
	defer func() {
		// 无法捕获异常
		if r := MyRecover(); r != nil {
			fmt.Println(r)
		}
	}()
	panic(1)
}

func MyRecover() interface{} {
	log.Println("trace...")
	return recover()
}
```
```go
func main() {
	defer func() {
		defer func() {
			// 无法捕获异常
			if r := recover(); r != nil {
				fmt.Println(r)
			}
		}()
	}()
	panic(1)
}
```
```go
func main() {
	// 无法捕获异常
	defer recover()
	panic(1)
}
```
如果是由java程序员转行的，可能会更喜欢以下写法
```go
func run() (param interface{}, err error){
	defer func(){
		if r := recover(); r != nil {
			err = fmt.Errorf("%v", r)
		}
	}

	err = f1()
	Panic(err)

	err = f2()
	Panic(err)

	return nil
}

func Panic(err error) {
	if err != nil {
		panic(err)
	}
}
```
写法更简洁，但是性能会差一些